<a href="https://colab.research.google.com/github/JayAld/CCST-Activities/blob/main/myFirstRProgram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. My first R Programming

In [16]:
myString <- "I love R Programming"

print(myString)

[1] "I love R Program"

2. Data Types and Variables

In [17]:
myString <- "I love R Programing"
wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE

print(myString)

[1] "I love R Programing"

3. Numerical Operators

In [18]:
x <- 10
y <- 3

add <- x + y
sub <- x - y
mul <- x * y
div <- x / y

print(add)
print(sub)
print(mul)
print(div)

[1] 13
[1] 7
[1] 30
[1] 3.333333

4. User Input

In [19]:
name <- readline("Enter name: ")

print(name)

Enter name: Rene Baterbonia
[1] "Rene Baterbonia"

5. Decision Making

In [20]:
grade <- 80

if (grade < 75){
  print("Failed")
}else{
  print("Passed")
}

[1] "Passed"

6. Loop

In [21]:
for(i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. Function

In [25]:
addNumber <- function(a,b){
  return(a+b)
}

addNumber(3,7)

[1] 10

8. Vectors

In [26]:
grades <- c(98,80,91,88,96)

grades

cat("MEAN: ", mean(grades))
cat("\nMAX: ", max(grades))
cat("\nMIN: ", min(grades))
cat("\nLENGTH: ", length(grades))
cat("\nMEDIAN: ", median(grades))

[1] 98 80 91 88 96

MEAN:  90.6
MAX:  98
MIN:  80
LENGTH:  5
MEDIAN:  91

9. Matrices

In [27]:
A <- matrix(c(1,2,3,4,5,6),nrow = 2)

A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

10. Lists

In [39]:
student <- list(
  name = "Pepito",
  course = "BSCS",
  grade = 75
)

student

$name
[1] "Pepito"

$course
[1] "BSCS"

$grade
[1] 75

11. Dataframe

In [40]:
students <- data.frame(
  name = c("Pepito","Eliza","Anna"),
  course = c("BSCS","BSIT","BSA"),
  grade = c(78, 80, 79)
)

students

  name   course grade
1 Pepito BSCS   78
2 Eliza  BSIT   80
3 Anna   BSA    79

12. Write to CSV

In [41]:
write.csv(students,"students.csv")

13. Read CSV File

In [42]:
data <- read.csv("students.csv")

head(data)
summary(data)

  X name   course grade
1 1 Pepito BSCS   78
2 2 Eliza  BSIT   80
3 3 Anna   BSA    79

       X              name         course      grade
 Min.   :1.0   Length   :3   Length   :3   Min.   :78.0
 1st Qu.:1.5   N.unique :3   N.unique :3   1st Qu.:78.5
 Median :2.0   N.blank  :0   N.blank  :0   Median :79.0
 Mean   :2.0   Min.nchar:4   Min.nchar:3   Mean   :79.0
 3rd Qu.:2.5   Max.nchar:6   Max.nchar:4   3rd Qu.:79.5
 Max.   :3.0                               Max.   :80.0